Fix horizontal scroll bug
DSACMS/open pull request #35
Opened 2024-07-16 17:49 UTC by Firebird1029

## Fix horizontal scroll bug

## Problem

On mobile, there is a horizontal scroll caused by text that overflows the cards. By adding an overflow CSS property, this removes the issue. Some other compile-time issues were also resolved.

## Solution

Also, some of the issues brought up in https://github.com/DSACMS/open/issues/23 do not appear when the website is tested locally, such as the menu. The deployed website at dsacms.github.io/open is probably just an outdated build.

2024-07-25 14:04 UTC, decause-gov requested changes
@IsaacMilarky and @natalialuzuriaga should give this a look also now that we're all back. `projects.liquid` looks legit, but I'm not sure about `repos.js`. Thoughts?

2024-07-25 14:04 UTC, decause-gov commented on site/_data/repos.js
> +  // "CMSgov/easi-app": {
Are we just commenting out this one entry?

2024-07-25 14:04 UTC, decause-gov commented on site/projects.liquid
> +        <div class="usa-card__container" style="overflow-x: scroll;">
This is the fix must be?

2024-07-26 04:26 UTC, Firebird1029 commented on site/_data/repos.js
> +  // "CMSgov/easi-app": {
This entry messes up the script for some reason, I figured the repo was set to private or deleted

2024-07-26 04:26 UTC, Firebird1029 commented on site/projects.liquid
> +        <div class="usa-card__container" style="overflow-x: scroll;">
Yes! The menu bug was already fixed when I cloned the repo, so I just had to fix the overflow issue

2024-07-26 12:24 UTC, decause-gov commented on site/_data/repos.js
> +  // "CMSgov/easi-app": {
Aha! I figured it out I reckon. Seems as though the repo has been transferred between CMS orgs! It is now hosted at https://github.com/CMS-Enterprise/easi-app!

easi-app is one of our most active oss projects, so we don't want to just skip or ignore it. For now, could we just manually update/rename the `repos.js` entry with the new URL/path, and move the associated `_data` accordingly?

@IsaacMilarky This seems like it will be a relatively rare occurrence, but an edgecase I suppose we should check for and catch? Let's ship this bugfix for now as-is, but file a new ticket for "Check for whether a repo has been transferred between CMS GitHub orgs."

2024-07-26 15:30 UTC, IsaacMilarky commented on site/_data/repos.js
> +  // "CMSgov/easi-app": {
There is an API endpoint to check to see if a repository was moved and it returns the new location so we could set up a method to check for that. 

The endpoint is in the format `https://api.github.com/repos/<repo_group>/<repo_name>` and will tell you the new location if the repository has been moved. 

For now we can just rename it but we could have some additional resolution logic in theory.

2024-07-31 16:59 UTC, decause-gov approved these changes
LGTM +1 🚢 🐛 🔧

2024-08-01 13:19 UTC, merged

2024-08-01 15:03 UTC, natalialuzuriaga commented
@Firebird1029 yup you are completely right with the deployed website being an outdated build. For some reason, the `deploy` jobs was skipped in the last couple of PRs when main was updated but now it looks like that job is running fine now and the website is up to date

2024-08-01 18:58 UTC, Firebird1029 commented
@natalialuzuriaga Something weird is happening -- looks like none of the bugs are fixed at https://dsacms.github.io/open/projects/ but the `deploy` job (or one of the jobs) definitely ran because, on the website, I see the repo I created yesterday in the DSACMS Github org, so the script ran very recently. But all the frontend problems are still there despite working locally.